### ISSUE TITLE
EventTextBuilder doesn't work

### ISSUE THREAD

**Issue by caiogranero** [Skyost/FlutterWeekView#18]
**Description:**

I'm trying to use the EventTextBuilder attribute of FlutterWeekViewEvent class but i'm having problem with they parameters. His declaration expected 4 parameters but he is calling with 5.

expected: https://github.com/Skyost/FlutterWeekView/blob/2a3e223c26424b300aeb1d1951a9ca324d9d3957/lib/src/day_view.dart#L16

actual call: https://github.com/Skyost/FlutterWeekView/blob/2a3e223c26424b300aeb1d1951a9ca324d9d3957/lib/src/event.dart#L78

Am i doing this in the wrong way? I made a fork of the repository and change the Function declaration to expected 5 parameters and its working.

**My code**

```
FlutterWeekViewEvent(title: "",
     start: start,
     end: end,
     description: "",
     textStyle: themeData.textTheme.body2,
     padding: EdgeInsets.only(left: 27, top: 13),
     margin: EdgeInsets.only(left: 16, right: 28, top: 1, bottom: 1),
     onTap: onTap,
     onLongPress: onLongPress,
     eventTextBuilder: (BuildContext context, DayView dayView, double height, double width) {
     return Container(); 
});
```

**Console:**

```

════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building DayView(dirty, state: _DayViewState#129c3):
Closure call with mismatched arguments: function 'new CloseScheduleWeekViewEvent.<anonymous closure>'
Receiver: Closure: (BuildContext, DayView, double, double) => Column
Tried calling: new CloseScheduleWeekViewEvent.<anonymous closure>(Instance of 'CloseScheduleWeekViewEvent', Instance of 'StatefulElement', Instance of 'DayView', 213.0, 334.42857142857144)
Found: new CloseScheduleWeekViewEvent.<anonymous closure>(BuildContext, DayView, double, double) => Column

The relevant error-causing widget was
    DayView 
lib\…\appointment\appointment_timeline.dart:44
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      FlutterWeekViewEvent.build 
package:flutter_week_view/src/event.dart:78
#2      _EventDrawProperties.createWidget 
package:flutter_week_view/src/day_view.dart:439
#3      _DayViewState.createMainWidget.<anonymous closure> 
package:flutter_week_view/src/day_view.dart:156
#4      MappedIterator.moveNext  (dart:_internal/iterable.dart:395:18)
...
```

**Comment by Skyost** [comment]
You're right, thank you !
