### ISSUE TITLE
ScrollController not attached to any scroll views

### ISSUE THREAD

**Issue by jaumard** [Skyost/FlutterWeekView#85]
**Describe the bug**
I have put a WeekView inside a `TabBarView`, once I click on the icon to move to the WeekView tab I get this error:

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
#3      ZoomableHeadersWidgetState.scrollToInitialTime (package:flutter_week_view/src/widgets/zoomable_header_widget.dart:184:48)
#4      _WeekViewState.scrollToInitialTime (package:flutter_week_view/src/widgets/week_view.dart:194:11)
#5      ZoomableHeadersWidgetState.scheduleScrollToInitialTime.<anonymous closure> (package:flutter_week_view/src/widgets/zoomable_header_widget.dart:167:41)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#12     _invoke (dart:ui/hooks.dart:166:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#14     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)

```

I'm using last flutter stable and flutter_week_view v1.2.0.

Thanks for this cool widget!

**Comment by diegotori** [comment]
@Skyost this issue is due to the widget's scroll controller not checking for clients before interacting with it. In other words, `ZoomableHeaderWidget.scrollToInitialTime()` needs to be changed to the following:

```dart
  void scrollToInitialTime() {
    if (mounted && verticalScrollController != null 
      && verticalScrollController.hasClients()) {
      double topOffset = calculateTopOffset(
          HourMinute.fromDateTime(dateTime: widget.initialTime));
      verticalScrollController!.jumpTo(math.min(
          topOffset, verticalScrollController!.position.maxScrollExtent));
    }
  }
```

Please let me know if this suffices.
